"""add reports table and relationships with client and employee

Revision ID: 35272138aae4
Revises: c2fd47ec53c8
Create Date: 2023-09-26 12:50:14.578075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35272138aae4'
down_revision = 'c2fd47ec53c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_of_report', sa.String(), nullable=False),
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_name'], ['clients.name'], name=op.f('fk_reports_client_name_clients')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_reports_employee_id_employees')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
