"""add columns to doctor and clients, establish realtionship

Revision ID: 495671bae250
Revises: fed3b344d8ee
Create Date: 2023-09-24 14:10:10.622593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495671bae250'
down_revision = 'fed3b344d8ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_clients')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_clients_doctor_id_doctors'), 'doctors', ['doctor_id'], ['id'])

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_clients_doctor_id_doctors'), type_='foreignkey')
        batch_op.drop_column('doctor_id')
        batch_op.drop_column('age')
        batch_op.drop_column('name')

    op.create_table('_alembic_tmp_clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name='fk_clients_doctor_id_doctors'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
