"""add columns for inventory

Revision ID: c2fd47ec53c8
Revises: 452314c0d320
Create Date: 2023-09-26 11:51:05.695312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2fd47ec53c8'
down_revision = '452314c0d320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('count_inventory', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('instructions', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.drop_column('instructions')
        batch_op.drop_column('count_inventory')
        batch_op.drop_column('inventory')

    # ### end Alembic commands ###
