"""add columns to employee and medtimes

Revision ID: c9336ef1de21
Revises: 74e4e41c2ebe
Create Date: 2023-10-06 16:23:40.881590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9336ef1de21'
down_revision = '74e4e41c2ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.String(), nullable=True))

    with op.batch_alter_table('med_times', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('med_times', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('number')

    # ### end Alembic commands ###
